### PR TITLE
feat: allow factory to destroy forwarders

### PR DESCRIPTION
**Pull request by aleksuss**

### CODE REVIEW

**Review by raventid — APPROVED** [review]
Cannot see any serious issues, LGTM 👍

**Review by birchmd — APPROVED** [review]
Nice work!

**Comment by aleksuss** [comment]
Guys, take a look please at this commit [e982984](https://github.com/aurora-is-near/aurora-forwarder-contracts/pull/25/commits/e982984e1eeb3a2da71eb9be7f29e876a3b343aa)
cc @birchmd @raventid

**Review by birchmd — APPROVED** [review]

**Review by raventid — APPROVED** [review]
Looks good

**Review by pustovalov — APPROVED** [review]

**Pull request merged**
